<?php
/**
 * SettingsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya Public API (SDK)
 *
 * Public customer API for Relaya SDKs. Authenticated with a profile API token (`X-Profile-Token`). Staff Admin API is intentionally excluded from this contract. Scopes: profiles:read|write, inbox:read|write, webhooks:manage, billing:read|write. Профили, сообщения, инбокс, модули, вебхуки и биллинг.
 *
 * The version of the OpenAPI document: devel
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Relaya\Sdk\ApiException;
use Relaya\Sdk\Configuration;
use Relaya\Sdk\FormDataProcessor;
use Relaya\Sdk\HeaderSelector;
use Relaya\Sdk\ObjectSerializer;

/**
 * SettingsApi Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettingsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getProfilesProfileIdIntegrationsIntegrationSettingsUser' => [
            'application/json',
        ],
        'patchProfilesProfileIdIntegrationsIntegrationSettingsUser' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getProfilesProfileIdIntegrationsIntegrationSettingsUser
     *
     * Получить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \Relaya\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Relaya\Sdk\Model\MaxUserSettingsResponseBody|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel
     */
    public function getProfilesProfileIdIntegrationsIntegrationSettingsUser($profile_id, $integration, string $contentType = self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        list($response) = $this->getProfilesProfileIdIntegrationsIntegrationSettingsUserWithHttpInfo($profile_id, $integration, $contentType);
        return $response;
    }

    /**
     * Operation getProfilesProfileIdIntegrationsIntegrationSettingsUserWithHttpInfo
     *
     * Получить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \Relaya\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Relaya\Sdk\Model\MaxUserSettingsResponseBody|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProfilesProfileIdIntegrationsIntegrationSettingsUserWithHttpInfo($profile_id, $integration, string $contentType = self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        $request = $this->getProfilesProfileIdIntegrationsIntegrationSettingsUserRequest($profile_id, $integration, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\MaxUserSettingsResponseBody',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 502:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Relaya\Sdk\Model\MaxUserSettingsResponseBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\MaxUserSettingsResponseBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 502:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getProfilesProfileIdIntegrationsIntegrationSettingsUserAsync
     *
     * Получить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProfilesProfileIdIntegrationsIntegrationSettingsUserAsync($profile_id, $integration, string $contentType = self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        return $this->getProfilesProfileIdIntegrationsIntegrationSettingsUserAsyncWithHttpInfo($profile_id, $integration, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProfilesProfileIdIntegrationsIntegrationSettingsUserAsyncWithHttpInfo
     *
     * Получить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProfilesProfileIdIntegrationsIntegrationSettingsUserAsyncWithHttpInfo($profile_id, $integration, string $contentType = self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        $returnType = '\Relaya\Sdk\Model\MaxUserSettingsResponseBody';
        $request = $this->getProfilesProfileIdIntegrationsIntegrationSettingsUserRequest($profile_id, $integration, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProfilesProfileIdIntegrationsIntegrationSettingsUser'
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProfilesProfileIdIntegrationsIntegrationSettingsUserRequest($profile_id, $integration, string $contentType = self::contentTypes['getProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {

        // verify the required parameter 'profile_id' is set
        if ($profile_id === null || (is_array($profile_id) && count($profile_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $profile_id when calling getProfilesProfileIdIntegrationsIntegrationSettingsUser'
            );
        }

        // verify the required parameter 'integration' is set
        if ($integration === null || (is_array($integration) && count($integration) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $integration when calling getProfilesProfileIdIntegrationsIntegrationSettingsUser'
            );
        }


        $resourcePath = '/profiles/{profileId}/integrations/{integration}/settings/user';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($profile_id !== null) {
            $resourcePath = str_replace(
                '{' . 'profileId' . '}',
                ObjectSerializer::toPathValue($profile_id),
                $resourcePath
            );
        }
        // path params
        if ($integration !== null) {
            $resourcePath = str_replace(
                '{' . 'integration' . '}',
                ObjectSerializer::toPathValue($integration),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Profile-Token');
        if ($apiKey !== null) {
            $headers['X-Profile-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchProfilesProfileIdIntegrationsIntegrationSettingsUser
     *
     * Обновить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  \Relaya\Sdk\Model\MaxSetUserSettingsInputBody $max_set_user_settings_input_body Параметры JSON-запроса. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \Relaya\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Relaya\Sdk\Model\MaxUserSettingsResponseBody|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel
     */
    public function patchProfilesProfileIdIntegrationsIntegrationSettingsUser($profile_id, $integration, $max_set_user_settings_input_body, string $contentType = self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        list($response) = $this->patchProfilesProfileIdIntegrationsIntegrationSettingsUserWithHttpInfo($profile_id, $integration, $max_set_user_settings_input_body, $contentType);
        return $response;
    }

    /**
     * Operation patchProfilesProfileIdIntegrationsIntegrationSettingsUserWithHttpInfo
     *
     * Обновить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  \Relaya\Sdk\Model\MaxSetUserSettingsInputBody $max_set_user_settings_input_body Параметры JSON-запроса. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \Relaya\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Relaya\Sdk\Model\MaxUserSettingsResponseBody|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel|\Relaya\Sdk\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchProfilesProfileIdIntegrationsIntegrationSettingsUserWithHttpInfo($profile_id, $integration, $max_set_user_settings_input_body, string $contentType = self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        $request = $this->patchProfilesProfileIdIntegrationsIntegrationSettingsUserRequest($profile_id, $integration, $max_set_user_settings_input_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\MaxUserSettingsResponseBody',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                case 502:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Relaya\Sdk\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Relaya\Sdk\Model\MaxUserSettingsResponseBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\MaxUserSettingsResponseBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 502:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Relaya\Sdk\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation patchProfilesProfileIdIntegrationsIntegrationSettingsUserAsync
     *
     * Обновить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  \Relaya\Sdk\Model\MaxSetUserSettingsInputBody $max_set_user_settings_input_body Параметры JSON-запроса. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchProfilesProfileIdIntegrationsIntegrationSettingsUserAsync($profile_id, $integration, $max_set_user_settings_input_body, string $contentType = self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        return $this->patchProfilesProfileIdIntegrationsIntegrationSettingsUserAsyncWithHttpInfo($profile_id, $integration, $max_set_user_settings_input_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchProfilesProfileIdIntegrationsIntegrationSettingsUserAsyncWithHttpInfo
     *
     * Обновить настройки аккаунта (MAX)
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  \Relaya\Sdk\Model\MaxSetUserSettingsInputBody $max_set_user_settings_input_body Параметры JSON-запроса. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchProfilesProfileIdIntegrationsIntegrationSettingsUserAsyncWithHttpInfo($profile_id, $integration, $max_set_user_settings_input_body, string $contentType = self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {
        $returnType = '\Relaya\Sdk\Model\MaxUserSettingsResponseBody';
        $request = $this->patchProfilesProfileIdIntegrationsIntegrationSettingsUserRequest($profile_id, $integration, $max_set_user_settings_input_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchProfilesProfileIdIntegrationsIntegrationSettingsUser'
     *
     * @param  string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка. (required)
     * @param  string $integration Код интеграции профиля: например &#x60;max&#x60;, &#x60;vk&#x60;, &#x60;telegram&#x60;, &#x60;telegrambot&#x60;, &#x60;maxbot&#x60;, &#x60;whatsapp&#x60; или &#x60;email&#x60;. (required)
     * @param  \Relaya\Sdk\Model\MaxSetUserSettingsInputBody $max_set_user_settings_input_body Параметры JSON-запроса. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchProfilesProfileIdIntegrationsIntegrationSettingsUserRequest($profile_id, $integration, $max_set_user_settings_input_body, string $contentType = self::contentTypes['patchProfilesProfileIdIntegrationsIntegrationSettingsUser'][0])
    {

        // verify the required parameter 'profile_id' is set
        if ($profile_id === null || (is_array($profile_id) && count($profile_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $profile_id when calling patchProfilesProfileIdIntegrationsIntegrationSettingsUser'
            );
        }

        // verify the required parameter 'integration' is set
        if ($integration === null || (is_array($integration) && count($integration) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $integration when calling patchProfilesProfileIdIntegrationsIntegrationSettingsUser'
            );
        }

        // verify the required parameter 'max_set_user_settings_input_body' is set
        if ($max_set_user_settings_input_body === null || (is_array($max_set_user_settings_input_body) && count($max_set_user_settings_input_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $max_set_user_settings_input_body when calling patchProfilesProfileIdIntegrationsIntegrationSettingsUser'
            );
        }


        $resourcePath = '/profiles/{profileId}/integrations/{integration}/settings/user';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($profile_id !== null) {
            $resourcePath = str_replace(
                '{' . 'profileId' . '}',
                ObjectSerializer::toPathValue($profile_id),
                $resourcePath
            );
        }
        // path params
        if ($integration !== null) {
            $resourcePath = str_replace(
                '{' . 'integration' . '}',
                ObjectSerializer::toPathValue($integration),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($max_set_user_settings_input_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($max_set_user_settings_input_body));
            } else {
                $httpBody = $max_set_user_settings_input_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Profile-Token');
        if ($apiKey !== null) {
            $headers['X-Profile-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
