<?php
/**
 * AccountSettings
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * AccountSettings Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'schema' => 'string',
        'delay_send_messages_milliseconds' => 'int',
        'incoming_webhook' => 'string',
        'mark_incoming_messages_readed' => 'string',
        'mark_incoming_messages_readed_on_reply' => 'string',
        'outgoing_api_message_webhook' => 'string',
        'outgoing_message_webhook' => 'string',
        'outgoing_webhook' => 'string',
        'state_webhook' => 'string',
        'type_profile' => 'string',
        'webhook_url' => 'string',
        'webhook_url_token' => 'string',
        'wid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'schema' => 'uri',
        'delay_send_messages_milliseconds' => 'int64',
        'incoming_webhook' => null,
        'mark_incoming_messages_readed' => null,
        'mark_incoming_messages_readed_on_reply' => null,
        'outgoing_api_message_webhook' => null,
        'outgoing_message_webhook' => null,
        'outgoing_webhook' => null,
        'state_webhook' => null,
        'type_profile' => null,
        'webhook_url' => null,
        'webhook_url_token' => null,
        'wid' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'schema' => false,
        'delay_send_messages_milliseconds' => false,
        'incoming_webhook' => false,
        'mark_incoming_messages_readed' => false,
        'mark_incoming_messages_readed_on_reply' => false,
        'outgoing_api_message_webhook' => false,
        'outgoing_message_webhook' => false,
        'outgoing_webhook' => false,
        'state_webhook' => false,
        'type_profile' => false,
        'webhook_url' => false,
        'webhook_url_token' => false,
        'wid' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'schema' => '$schema',
        'delay_send_messages_milliseconds' => 'delaySendMessagesMilliseconds',
        'incoming_webhook' => 'incomingWebhook',
        'mark_incoming_messages_readed' => 'markIncomingMessagesReaded',
        'mark_incoming_messages_readed_on_reply' => 'markIncomingMessagesReadedOnReply',
        'outgoing_api_message_webhook' => 'outgoingAPIMessageWebhook',
        'outgoing_message_webhook' => 'outgoingMessageWebhook',
        'outgoing_webhook' => 'outgoingWebhook',
        'state_webhook' => 'stateWebhook',
        'type_profile' => 'typeProfile',
        'webhook_url' => 'webhookUrl',
        'webhook_url_token' => 'webhookUrlToken',
        'wid' => 'wid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'schema' => 'setSchema',
        'delay_send_messages_milliseconds' => 'setDelaySendMessagesMilliseconds',
        'incoming_webhook' => 'setIncomingWebhook',
        'mark_incoming_messages_readed' => 'setMarkIncomingMessagesReaded',
        'mark_incoming_messages_readed_on_reply' => 'setMarkIncomingMessagesReadedOnReply',
        'outgoing_api_message_webhook' => 'setOutgoingApiMessageWebhook',
        'outgoing_message_webhook' => 'setOutgoingMessageWebhook',
        'outgoing_webhook' => 'setOutgoingWebhook',
        'state_webhook' => 'setStateWebhook',
        'type_profile' => 'setTypeProfile',
        'webhook_url' => 'setWebhookUrl',
        'webhook_url_token' => 'setWebhookUrlToken',
        'wid' => 'setWid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'schema' => 'getSchema',
        'delay_send_messages_milliseconds' => 'getDelaySendMessagesMilliseconds',
        'incoming_webhook' => 'getIncomingWebhook',
        'mark_incoming_messages_readed' => 'getMarkIncomingMessagesReaded',
        'mark_incoming_messages_readed_on_reply' => 'getMarkIncomingMessagesReadedOnReply',
        'outgoing_api_message_webhook' => 'getOutgoingApiMessageWebhook',
        'outgoing_message_webhook' => 'getOutgoingMessageWebhook',
        'outgoing_webhook' => 'getOutgoingWebhook',
        'state_webhook' => 'getStateWebhook',
        'type_profile' => 'getTypeProfile',
        'webhook_url' => 'getWebhookUrl',
        'webhook_url_token' => 'getWebhookUrlToken',
        'wid' => 'getWid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('schema', $data ?? [], null);
        $this->setIfExists('delay_send_messages_milliseconds', $data ?? [], null);
        $this->setIfExists('incoming_webhook', $data ?? [], null);
        $this->setIfExists('mark_incoming_messages_readed', $data ?? [], null);
        $this->setIfExists('mark_incoming_messages_readed_on_reply', $data ?? [], null);
        $this->setIfExists('outgoing_api_message_webhook', $data ?? [], null);
        $this->setIfExists('outgoing_message_webhook', $data ?? [], null);
        $this->setIfExists('outgoing_webhook', $data ?? [], null);
        $this->setIfExists('state_webhook', $data ?? [], null);
        $this->setIfExists('type_profile', $data ?? [], null);
        $this->setIfExists('webhook_url', $data ?? [], null);
        $this->setIfExists('webhook_url_token', $data ?? [], null);
        $this->setIfExists('wid', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['delay_send_messages_milliseconds'] === null) {
            $invalidProperties[] = "'delay_send_messages_milliseconds' can't be null";
        }
        if ($this->container['incoming_webhook'] === null) {
            $invalidProperties[] = "'incoming_webhook' can't be null";
        }
        if ($this->container['mark_incoming_messages_readed'] === null) {
            $invalidProperties[] = "'mark_incoming_messages_readed' can't be null";
        }
        if ($this->container['mark_incoming_messages_readed_on_reply'] === null) {
            $invalidProperties[] = "'mark_incoming_messages_readed_on_reply' can't be null";
        }
        if ($this->container['outgoing_api_message_webhook'] === null) {
            $invalidProperties[] = "'outgoing_api_message_webhook' can't be null";
        }
        if ($this->container['outgoing_message_webhook'] === null) {
            $invalidProperties[] = "'outgoing_message_webhook' can't be null";
        }
        if ($this->container['outgoing_webhook'] === null) {
            $invalidProperties[] = "'outgoing_webhook' can't be null";
        }
        if ($this->container['state_webhook'] === null) {
            $invalidProperties[] = "'state_webhook' can't be null";
        }
        if ($this->container['type_profile'] === null) {
            $invalidProperties[] = "'type_profile' can't be null";
        }
        if ($this->container['webhook_url'] === null) {
            $invalidProperties[] = "'webhook_url' can't be null";
        }
        if ($this->container['webhook_url_token'] === null) {
            $invalidProperties[] = "'webhook_url_token' can't be null";
        }
        if ($this->container['wid'] === null) {
            $invalidProperties[] = "'wid' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets schema
     *
     * @return string|null
     */
    public function getSchema()
    {
        return $this->container['schema'];
    }

    /**
     * Sets schema
     *
     * @param string|null $schema A URL to the JSON Schema for this object.
     *
     * @return self
     */
    public function setSchema($schema)
    {
        if (is_null($schema)) {
            throw new \InvalidArgumentException('non-nullable schema cannot be null');
        }
        $this->container['schema'] = $schema;

        return $this;
    }

    /**
     * Gets delay_send_messages_milliseconds
     *
     * @return int
     */
    public function getDelaySendMessagesMilliseconds()
    {
        return $this->container['delay_send_messages_milliseconds'];
    }

    /**
     * Sets delay_send_messages_milliseconds
     *
     * @param int $delay_send_messages_milliseconds delay_send_messages_milliseconds
     *
     * @return self
     */
    public function setDelaySendMessagesMilliseconds($delay_send_messages_milliseconds)
    {
        if (is_null($delay_send_messages_milliseconds)) {
            throw new \InvalidArgumentException('non-nullable delay_send_messages_milliseconds cannot be null');
        }
        $this->container['delay_send_messages_milliseconds'] = $delay_send_messages_milliseconds;

        return $this;
    }

    /**
     * Gets incoming_webhook
     *
     * @return string
     */
    public function getIncomingWebhook()
    {
        return $this->container['incoming_webhook'];
    }

    /**
     * Sets incoming_webhook
     *
     * @param string $incoming_webhook incoming_webhook
     *
     * @return self
     */
    public function setIncomingWebhook($incoming_webhook)
    {
        if (is_null($incoming_webhook)) {
            throw new \InvalidArgumentException('non-nullable incoming_webhook cannot be null');
        }
        $this->container['incoming_webhook'] = $incoming_webhook;

        return $this;
    }

    /**
     * Gets mark_incoming_messages_readed
     *
     * @return string
     */
    public function getMarkIncomingMessagesReaded()
    {
        return $this->container['mark_incoming_messages_readed'];
    }

    /**
     * Sets mark_incoming_messages_readed
     *
     * @param string $mark_incoming_messages_readed mark_incoming_messages_readed
     *
     * @return self
     */
    public function setMarkIncomingMessagesReaded($mark_incoming_messages_readed)
    {
        if (is_null($mark_incoming_messages_readed)) {
            throw new \InvalidArgumentException('non-nullable mark_incoming_messages_readed cannot be null');
        }
        $this->container['mark_incoming_messages_readed'] = $mark_incoming_messages_readed;

        return $this;
    }

    /**
     * Gets mark_incoming_messages_readed_on_reply
     *
     * @return string
     */
    public function getMarkIncomingMessagesReadedOnReply()
    {
        return $this->container['mark_incoming_messages_readed_on_reply'];
    }

    /**
     * Sets mark_incoming_messages_readed_on_reply
     *
     * @param string $mark_incoming_messages_readed_on_reply mark_incoming_messages_readed_on_reply
     *
     * @return self
     */
    public function setMarkIncomingMessagesReadedOnReply($mark_incoming_messages_readed_on_reply)
    {
        if (is_null($mark_incoming_messages_readed_on_reply)) {
            throw new \InvalidArgumentException('non-nullable mark_incoming_messages_readed_on_reply cannot be null');
        }
        $this->container['mark_incoming_messages_readed_on_reply'] = $mark_incoming_messages_readed_on_reply;

        return $this;
    }

    /**
     * Gets outgoing_api_message_webhook
     *
     * @return string
     */
    public function getOutgoingApiMessageWebhook()
    {
        return $this->container['outgoing_api_message_webhook'];
    }

    /**
     * Sets outgoing_api_message_webhook
     *
     * @param string $outgoing_api_message_webhook outgoing_api_message_webhook
     *
     * @return self
     */
    public function setOutgoingApiMessageWebhook($outgoing_api_message_webhook)
    {
        if (is_null($outgoing_api_message_webhook)) {
            throw new \InvalidArgumentException('non-nullable outgoing_api_message_webhook cannot be null');
        }
        $this->container['outgoing_api_message_webhook'] = $outgoing_api_message_webhook;

        return $this;
    }

    /**
     * Gets outgoing_message_webhook
     *
     * @return string
     */
    public function getOutgoingMessageWebhook()
    {
        return $this->container['outgoing_message_webhook'];
    }

    /**
     * Sets outgoing_message_webhook
     *
     * @param string $outgoing_message_webhook outgoing_message_webhook
     *
     * @return self
     */
    public function setOutgoingMessageWebhook($outgoing_message_webhook)
    {
        if (is_null($outgoing_message_webhook)) {
            throw new \InvalidArgumentException('non-nullable outgoing_message_webhook cannot be null');
        }
        $this->container['outgoing_message_webhook'] = $outgoing_message_webhook;

        return $this;
    }

    /**
     * Gets outgoing_webhook
     *
     * @return string
     */
    public function getOutgoingWebhook()
    {
        return $this->container['outgoing_webhook'];
    }

    /**
     * Sets outgoing_webhook
     *
     * @param string $outgoing_webhook outgoing_webhook
     *
     * @return self
     */
    public function setOutgoingWebhook($outgoing_webhook)
    {
        if (is_null($outgoing_webhook)) {
            throw new \InvalidArgumentException('non-nullable outgoing_webhook cannot be null');
        }
        $this->container['outgoing_webhook'] = $outgoing_webhook;

        return $this;
    }

    /**
     * Gets state_webhook
     *
     * @return string
     */
    public function getStateWebhook()
    {
        return $this->container['state_webhook'];
    }

    /**
     * Sets state_webhook
     *
     * @param string $state_webhook state_webhook
     *
     * @return self
     */
    public function setStateWebhook($state_webhook)
    {
        if (is_null($state_webhook)) {
            throw new \InvalidArgumentException('non-nullable state_webhook cannot be null');
        }
        $this->container['state_webhook'] = $state_webhook;

        return $this;
    }

    /**
     * Gets type_profile
     *
     * @return string
     */
    public function getTypeProfile()
    {
        return $this->container['type_profile'];
    }

    /**
     * Sets type_profile
     *
     * @param string $type_profile type_profile
     *
     * @return self
     */
    public function setTypeProfile($type_profile)
    {
        if (is_null($type_profile)) {
            throw new \InvalidArgumentException('non-nullable type_profile cannot be null');
        }
        $this->container['type_profile'] = $type_profile;

        return $this;
    }

    /**
     * Gets webhook_url
     *
     * @return string
     */
    public function getWebhookUrl()
    {
        return $this->container['webhook_url'];
    }

    /**
     * Sets webhook_url
     *
     * @param string $webhook_url webhook_url
     *
     * @return self
     */
    public function setWebhookUrl($webhook_url)
    {
        if (is_null($webhook_url)) {
            throw new \InvalidArgumentException('non-nullable webhook_url cannot be null');
        }
        $this->container['webhook_url'] = $webhook_url;

        return $this;
    }

    /**
     * Gets webhook_url_token
     *
     * @return string
     */
    public function getWebhookUrlToken()
    {
        return $this->container['webhook_url_token'];
    }

    /**
     * Sets webhook_url_token
     *
     * @param string $webhook_url_token webhook_url_token
     *
     * @return self
     */
    public function setWebhookUrlToken($webhook_url_token)
    {
        if (is_null($webhook_url_token)) {
            throw new \InvalidArgumentException('non-nullable webhook_url_token cannot be null');
        }
        $this->container['webhook_url_token'] = $webhook_url_token;

        return $this;
    }

    /**
     * Gets wid
     *
     * @return string
     */
    public function getWid()
    {
        return $this->container['wid'];
    }

    /**
     * Sets wid
     *
     * @param string $wid wid
     *
     * @return self
     */
    public function setWid($wid)
    {
        if (is_null($wid)) {
            throw new \InvalidArgumentException('non-nullable wid cannot be null');
        }
        $this->container['wid'] = $wid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


