<?php
/**
 * BackupProfileAuth
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * BackupProfileAuth Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BackupProfileAuth implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BackupProfileAuth';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'created' => '\DateTime',
        'login_available' => 'bool',
        'login_payload_json' => 'string',
        'profile_id' => 'string',
        'profile_json' => 'string',
        'qr_expires_at' => 'int',
        'qr_link' => 'string',
        'qr_polling_interval' => 'int',
        'qr_track_id' => 'string',
        'qr_ttl' => 'int',
        'sync_payload_json' => 'string',
        'token' => 'string',
        'updated' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'created' => 'date-time',
        'login_available' => null,
        'login_payload_json' => null,
        'profile_id' => null,
        'profile_json' => null,
        'qr_expires_at' => 'int64',
        'qr_link' => null,
        'qr_polling_interval' => 'int64',
        'qr_track_id' => null,
        'qr_ttl' => 'int64',
        'sync_payload_json' => null,
        'token' => null,
        'updated' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'created' => false,
        'login_available' => false,
        'login_payload_json' => false,
        'profile_id' => false,
        'profile_json' => false,
        'qr_expires_at' => false,
        'qr_link' => false,
        'qr_polling_interval' => false,
        'qr_track_id' => false,
        'qr_ttl' => false,
        'sync_payload_json' => false,
        'token' => false,
        'updated' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'created' => 'created',
        'login_available' => 'loginAvailable',
        'login_payload_json' => 'loginPayloadJson',
        'profile_id' => 'profileId',
        'profile_json' => 'profileJson',
        'qr_expires_at' => 'qrExpiresAt',
        'qr_link' => 'qrLink',
        'qr_polling_interval' => 'qrPollingInterval',
        'qr_track_id' => 'qrTrackId',
        'qr_ttl' => 'qrTtl',
        'sync_payload_json' => 'syncPayloadJson',
        'token' => 'token',
        'updated' => 'updated'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'created' => 'setCreated',
        'login_available' => 'setLoginAvailable',
        'login_payload_json' => 'setLoginPayloadJson',
        'profile_id' => 'setProfileId',
        'profile_json' => 'setProfileJson',
        'qr_expires_at' => 'setQrExpiresAt',
        'qr_link' => 'setQrLink',
        'qr_polling_interval' => 'setQrPollingInterval',
        'qr_track_id' => 'setQrTrackId',
        'qr_ttl' => 'setQrTtl',
        'sync_payload_json' => 'setSyncPayloadJson',
        'token' => 'setToken',
        'updated' => 'setUpdated'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'created' => 'getCreated',
        'login_available' => 'getLoginAvailable',
        'login_payload_json' => 'getLoginPayloadJson',
        'profile_id' => 'getProfileId',
        'profile_json' => 'getProfileJson',
        'qr_expires_at' => 'getQrExpiresAt',
        'qr_link' => 'getQrLink',
        'qr_polling_interval' => 'getQrPollingInterval',
        'qr_track_id' => 'getQrTrackId',
        'qr_ttl' => 'getQrTtl',
        'sync_payload_json' => 'getSyncPayloadJson',
        'token' => 'getToken',
        'updated' => 'getUpdated'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('login_available', $data ?? [], null);
        $this->setIfExists('login_payload_json', $data ?? [], null);
        $this->setIfExists('profile_id', $data ?? [], null);
        $this->setIfExists('profile_json', $data ?? [], null);
        $this->setIfExists('qr_expires_at', $data ?? [], null);
        $this->setIfExists('qr_link', $data ?? [], null);
        $this->setIfExists('qr_polling_interval', $data ?? [], null);
        $this->setIfExists('qr_track_id', $data ?? [], null);
        $this->setIfExists('qr_ttl', $data ?? [], null);
        $this->setIfExists('sync_payload_json', $data ?? [], null);
        $this->setIfExists('token', $data ?? [], null);
        $this->setIfExists('updated', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ($this->container['login_available'] === null) {
            $invalidProperties[] = "'login_available' can't be null";
        }
        if ($this->container['login_payload_json'] === null) {
            $invalidProperties[] = "'login_payload_json' can't be null";
        }
        if ($this->container['profile_id'] === null) {
            $invalidProperties[] = "'profile_id' can't be null";
        }
        if ($this->container['profile_json'] === null) {
            $invalidProperties[] = "'profile_json' can't be null";
        }
        if ($this->container['qr_expires_at'] === null) {
            $invalidProperties[] = "'qr_expires_at' can't be null";
        }
        if ($this->container['qr_link'] === null) {
            $invalidProperties[] = "'qr_link' can't be null";
        }
        if ($this->container['qr_polling_interval'] === null) {
            $invalidProperties[] = "'qr_polling_interval' can't be null";
        }
        if ($this->container['qr_track_id'] === null) {
            $invalidProperties[] = "'qr_track_id' can't be null";
        }
        if ($this->container['qr_ttl'] === null) {
            $invalidProperties[] = "'qr_ttl' can't be null";
        }
        if ($this->container['sync_payload_json'] === null) {
            $invalidProperties[] = "'sync_payload_json' can't be null";
        }
        if ($this->container['token'] === null) {
            $invalidProperties[] = "'token' can't be null";
        }
        if ($this->container['updated'] === null) {
            $invalidProperties[] = "'updated' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created created
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets login_available
     *
     * @return bool
     */
    public function getLoginAvailable()
    {
        return $this->container['login_available'];
    }

    /**
     * Sets login_available
     *
     * @param bool $login_available login_available
     *
     * @return self
     */
    public function setLoginAvailable($login_available)
    {
        if (is_null($login_available)) {
            throw new \InvalidArgumentException('non-nullable login_available cannot be null');
        }
        $this->container['login_available'] = $login_available;

        return $this;
    }

    /**
     * Gets login_payload_json
     *
     * @return string
     */
    public function getLoginPayloadJson()
    {
        return $this->container['login_payload_json'];
    }

    /**
     * Sets login_payload_json
     *
     * @param string $login_payload_json login_payload_json
     *
     * @return self
     */
    public function setLoginPayloadJson($login_payload_json)
    {
        if (is_null($login_payload_json)) {
            throw new \InvalidArgumentException('non-nullable login_payload_json cannot be null');
        }
        $this->container['login_payload_json'] = $login_payload_json;

        return $this;
    }

    /**
     * Gets profile_id
     *
     * @return string
     */
    public function getProfileId()
    {
        return $this->container['profile_id'];
    }

    /**
     * Sets profile_id
     *
     * @param string $profile_id profile_id
     *
     * @return self
     */
    public function setProfileId($profile_id)
    {
        if (is_null($profile_id)) {
            throw new \InvalidArgumentException('non-nullable profile_id cannot be null');
        }
        $this->container['profile_id'] = $profile_id;

        return $this;
    }

    /**
     * Gets profile_json
     *
     * @return string
     */
    public function getProfileJson()
    {
        return $this->container['profile_json'];
    }

    /**
     * Sets profile_json
     *
     * @param string $profile_json profile_json
     *
     * @return self
     */
    public function setProfileJson($profile_json)
    {
        if (is_null($profile_json)) {
            throw new \InvalidArgumentException('non-nullable profile_json cannot be null');
        }
        $this->container['profile_json'] = $profile_json;

        return $this;
    }

    /**
     * Gets qr_expires_at
     *
     * @return int
     */
    public function getQrExpiresAt()
    {
        return $this->container['qr_expires_at'];
    }

    /**
     * Sets qr_expires_at
     *
     * @param int $qr_expires_at qr_expires_at
     *
     * @return self
     */
    public function setQrExpiresAt($qr_expires_at)
    {
        if (is_null($qr_expires_at)) {
            throw new \InvalidArgumentException('non-nullable qr_expires_at cannot be null');
        }
        $this->container['qr_expires_at'] = $qr_expires_at;

        return $this;
    }

    /**
     * Gets qr_link
     *
     * @return string
     */
    public function getQrLink()
    {
        return $this->container['qr_link'];
    }

    /**
     * Sets qr_link
     *
     * @param string $qr_link qr_link
     *
     * @return self
     */
    public function setQrLink($qr_link)
    {
        if (is_null($qr_link)) {
            throw new \InvalidArgumentException('non-nullable qr_link cannot be null');
        }
        $this->container['qr_link'] = $qr_link;

        return $this;
    }

    /**
     * Gets qr_polling_interval
     *
     * @return int
     */
    public function getQrPollingInterval()
    {
        return $this->container['qr_polling_interval'];
    }

    /**
     * Sets qr_polling_interval
     *
     * @param int $qr_polling_interval qr_polling_interval
     *
     * @return self
     */
    public function setQrPollingInterval($qr_polling_interval)
    {
        if (is_null($qr_polling_interval)) {
            throw new \InvalidArgumentException('non-nullable qr_polling_interval cannot be null');
        }
        $this->container['qr_polling_interval'] = $qr_polling_interval;

        return $this;
    }

    /**
     * Gets qr_track_id
     *
     * @return string
     */
    public function getQrTrackId()
    {
        return $this->container['qr_track_id'];
    }

    /**
     * Sets qr_track_id
     *
     * @param string $qr_track_id qr_track_id
     *
     * @return self
     */
    public function setQrTrackId($qr_track_id)
    {
        if (is_null($qr_track_id)) {
            throw new \InvalidArgumentException('non-nullable qr_track_id cannot be null');
        }
        $this->container['qr_track_id'] = $qr_track_id;

        return $this;
    }

    /**
     * Gets qr_ttl
     *
     * @return int
     */
    public function getQrTtl()
    {
        return $this->container['qr_ttl'];
    }

    /**
     * Sets qr_ttl
     *
     * @param int $qr_ttl qr_ttl
     *
     * @return self
     */
    public function setQrTtl($qr_ttl)
    {
        if (is_null($qr_ttl)) {
            throw new \InvalidArgumentException('non-nullable qr_ttl cannot be null');
        }
        $this->container['qr_ttl'] = $qr_ttl;

        return $this;
    }

    /**
     * Gets sync_payload_json
     *
     * @return string
     */
    public function getSyncPayloadJson()
    {
        return $this->container['sync_payload_json'];
    }

    /**
     * Sets sync_payload_json
     *
     * @param string $sync_payload_json sync_payload_json
     *
     * @return self
     */
    public function setSyncPayloadJson($sync_payload_json)
    {
        if (is_null($sync_payload_json)) {
            throw new \InvalidArgumentException('non-nullable sync_payload_json cannot be null');
        }
        $this->container['sync_payload_json'] = $sync_payload_json;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string $token token
     *
     * @return self
     */
    public function setToken($token)
    {
        if (is_null($token)) {
            throw new \InvalidArgumentException('non-nullable token cannot be null');
        }
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param \DateTime $updated updated
     *
     * @return self
     */
    public function setUpdated($updated)
    {
        if (is_null($updated)) {
            throw new \InvalidArgumentException('non-nullable updated cannot be null');
        }
        $this->container['updated'] = $updated;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


