<?php
/**
 * DashboardSetup
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * DashboardSetup Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DashboardSetup implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DashboardSetup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'has_connected_profile' => 'bool',
        'has_outgoing_messages' => 'bool',
        'has_profiles' => 'bool',
        'has_quota' => 'bool',
        'has_webhook' => 'bool',
        'next_step' => 'string',
        'progress_percent' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'has_connected_profile' => null,
        'has_outgoing_messages' => null,
        'has_profiles' => null,
        'has_quota' => null,
        'has_webhook' => null,
        'next_step' => null,
        'progress_percent' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'has_connected_profile' => false,
        'has_outgoing_messages' => false,
        'has_profiles' => false,
        'has_quota' => false,
        'has_webhook' => false,
        'next_step' => false,
        'progress_percent' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'has_connected_profile' => 'hasConnectedProfile',
        'has_outgoing_messages' => 'hasOutgoingMessages',
        'has_profiles' => 'hasProfiles',
        'has_quota' => 'hasQuota',
        'has_webhook' => 'hasWebhook',
        'next_step' => 'nextStep',
        'progress_percent' => 'progressPercent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'has_connected_profile' => 'setHasConnectedProfile',
        'has_outgoing_messages' => 'setHasOutgoingMessages',
        'has_profiles' => 'setHasProfiles',
        'has_quota' => 'setHasQuota',
        'has_webhook' => 'setHasWebhook',
        'next_step' => 'setNextStep',
        'progress_percent' => 'setProgressPercent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'has_connected_profile' => 'getHasConnectedProfile',
        'has_outgoing_messages' => 'getHasOutgoingMessages',
        'has_profiles' => 'getHasProfiles',
        'has_quota' => 'getHasQuota',
        'has_webhook' => 'getHasWebhook',
        'next_step' => 'getNextStep',
        'progress_percent' => 'getProgressPercent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('has_connected_profile', $data ?? [], null);
        $this->setIfExists('has_outgoing_messages', $data ?? [], null);
        $this->setIfExists('has_profiles', $data ?? [], null);
        $this->setIfExists('has_quota', $data ?? [], null);
        $this->setIfExists('has_webhook', $data ?? [], null);
        $this->setIfExists('next_step', $data ?? [], null);
        $this->setIfExists('progress_percent', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['has_connected_profile'] === null) {
            $invalidProperties[] = "'has_connected_profile' can't be null";
        }
        if ($this->container['has_outgoing_messages'] === null) {
            $invalidProperties[] = "'has_outgoing_messages' can't be null";
        }
        if ($this->container['has_profiles'] === null) {
            $invalidProperties[] = "'has_profiles' can't be null";
        }
        if ($this->container['has_quota'] === null) {
            $invalidProperties[] = "'has_quota' can't be null";
        }
        if ($this->container['has_webhook'] === null) {
            $invalidProperties[] = "'has_webhook' can't be null";
        }
        if ($this->container['next_step'] === null) {
            $invalidProperties[] = "'next_step' can't be null";
        }
        if ($this->container['progress_percent'] === null) {
            $invalidProperties[] = "'progress_percent' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets has_connected_profile
     *
     * @return bool
     */
    public function getHasConnectedProfile()
    {
        return $this->container['has_connected_profile'];
    }

    /**
     * Sets has_connected_profile
     *
     * @param bool $has_connected_profile has_connected_profile
     *
     * @return self
     */
    public function setHasConnectedProfile($has_connected_profile)
    {
        if (is_null($has_connected_profile)) {
            throw new \InvalidArgumentException('non-nullable has_connected_profile cannot be null');
        }
        $this->container['has_connected_profile'] = $has_connected_profile;

        return $this;
    }

    /**
     * Gets has_outgoing_messages
     *
     * @return bool
     */
    public function getHasOutgoingMessages()
    {
        return $this->container['has_outgoing_messages'];
    }

    /**
     * Sets has_outgoing_messages
     *
     * @param bool $has_outgoing_messages has_outgoing_messages
     *
     * @return self
     */
    public function setHasOutgoingMessages($has_outgoing_messages)
    {
        if (is_null($has_outgoing_messages)) {
            throw new \InvalidArgumentException('non-nullable has_outgoing_messages cannot be null');
        }
        $this->container['has_outgoing_messages'] = $has_outgoing_messages;

        return $this;
    }

    /**
     * Gets has_profiles
     *
     * @return bool
     */
    public function getHasProfiles()
    {
        return $this->container['has_profiles'];
    }

    /**
     * Sets has_profiles
     *
     * @param bool $has_profiles has_profiles
     *
     * @return self
     */
    public function setHasProfiles($has_profiles)
    {
        if (is_null($has_profiles)) {
            throw new \InvalidArgumentException('non-nullable has_profiles cannot be null');
        }
        $this->container['has_profiles'] = $has_profiles;

        return $this;
    }

    /**
     * Gets has_quota
     *
     * @return bool
     */
    public function getHasQuota()
    {
        return $this->container['has_quota'];
    }

    /**
     * Sets has_quota
     *
     * @param bool $has_quota has_quota
     *
     * @return self
     */
    public function setHasQuota($has_quota)
    {
        if (is_null($has_quota)) {
            throw new \InvalidArgumentException('non-nullable has_quota cannot be null');
        }
        $this->container['has_quota'] = $has_quota;

        return $this;
    }

    /**
     * Gets has_webhook
     *
     * @return bool
     */
    public function getHasWebhook()
    {
        return $this->container['has_webhook'];
    }

    /**
     * Sets has_webhook
     *
     * @param bool $has_webhook has_webhook
     *
     * @return self
     */
    public function setHasWebhook($has_webhook)
    {
        if (is_null($has_webhook)) {
            throw new \InvalidArgumentException('non-nullable has_webhook cannot be null');
        }
        $this->container['has_webhook'] = $has_webhook;

        return $this;
    }

    /**
     * Gets next_step
     *
     * @return string
     */
    public function getNextStep()
    {
        return $this->container['next_step'];
    }

    /**
     * Sets next_step
     *
     * @param string $next_step Next setup step code
     *
     * @return self
     */
    public function setNextStep($next_step)
    {
        if (is_null($next_step)) {
            throw new \InvalidArgumentException('non-nullable next_step cannot be null');
        }
        $this->container['next_step'] = $next_step;

        return $this;
    }

    /**
     * Gets progress_percent
     *
     * @return int
     */
    public function getProgressPercent()
    {
        return $this->container['progress_percent'];
    }

    /**
     * Sets progress_percent
     *
     * @param int $progress_percent Progress in percent
     *
     * @return self
     */
    public function setProgressPercent($progress_percent)
    {
        if (is_null($progress_percent)) {
            throw new \InvalidArgumentException('non-nullable progress_percent cannot be null');
        }
        $this->container['progress_percent'] = $progress_percent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


