<?php
/**
 * ProfileReadinessBody
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya Public API (SDK)
 *
 * Public customer API for Relaya SDKs. Authenticated with a profile API token (`X-Profile-Token`). Staff Admin API is intentionally excluded from this contract. Scopes: profiles:read|write, inbox:read|write, webhooks:manage, billing:read|write. Профили, сообщения, инбокс, модули, вебхуки и биллинг.
 *
 * The version of the OpenAPI document: devel
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * ProfileReadinessBody Class Doc Comment
 *
 * @category Class
 * @description Объект модели API.
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProfileReadinessBody implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProfileReadinessBody';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'checks' => '\Relaya\Sdk\Model\ProfileReadinessChecksBody',
        'code' => 'string',
        'label' => 'string',
        'primary_action' => 'string',
        'tone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'checks' => null,
        'code' => null,
        'label' => null,
        'primary_action' => null,
        'tone' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'checks' => false,
        'code' => false,
        'label' => false,
        'primary_action' => false,
        'tone' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'checks' => 'checks',
        'code' => 'code',
        'label' => 'label',
        'primary_action' => 'primaryAction',
        'tone' => 'tone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'checks' => 'setChecks',
        'code' => 'setCode',
        'label' => 'setLabel',
        'primary_action' => 'setPrimaryAction',
        'tone' => 'setTone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'checks' => 'getChecks',
        'code' => 'getCode',
        'label' => 'getLabel',
        'primary_action' => 'getPrimaryAction',
        'tone' => 'getTone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PRIMARY_ACTION_CONNECT = 'connect';
    public const PRIMARY_ACTION_RENEW = 'renew';
    public const PRIMARY_ACTION_WEBHOOKS = 'webhooks';
    public const PRIMARY_ACTION_INBOX = 'inbox';
    public const PRIMARY_ACTION_TEST = 'test';
    public const PRIMARY_ACTION_NONE = 'none';
    public const TONE_OK = 'ok';
    public const TONE_WARN = 'warn';
    public const TONE_FAIL = 'fail';
    public const TONE_PENDING = 'pending';
    public const TONE_SKIP = 'skip';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPrimaryActionAllowableValues()
    {
        return [
            self::PRIMARY_ACTION_CONNECT,
            self::PRIMARY_ACTION_RENEW,
            self::PRIMARY_ACTION_WEBHOOKS,
            self::PRIMARY_ACTION_INBOX,
            self::PRIMARY_ACTION_TEST,
            self::PRIMARY_ACTION_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getToneAllowableValues()
    {
        return [
            self::TONE_OK,
            self::TONE_WARN,
            self::TONE_FAIL,
            self::TONE_PENDING,
            self::TONE_SKIP,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('checks', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('primary_action', $data ?? [], null);
        $this->setIfExists('tone', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['checks'] === null) {
            $invalidProperties[] = "'checks' can't be null";
        }
        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['label'] === null) {
            $invalidProperties[] = "'label' can't be null";
        }
        if ($this->container['primary_action'] === null) {
            $invalidProperties[] = "'primary_action' can't be null";
        }
        $allowedValues = $this->getPrimaryActionAllowableValues();
        if (!is_null($this->container['primary_action']) && !in_array($this->container['primary_action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'primary_action', must be one of '%s'",
                $this->container['primary_action'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['tone'] === null) {
            $invalidProperties[] = "'tone' can't be null";
        }
        $allowedValues = $this->getToneAllowableValues();
        if (!is_null($this->container['tone']) && !in_array($this->container['tone'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tone', must be one of '%s'",
                $this->container['tone'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets checks
     *
     * @return \Relaya\Sdk\Model\ProfileReadinessChecksBody
     */
    public function getChecks()
    {
        return $this->container['checks'];
    }

    /**
     * Sets checks
     *
     * @param \Relaya\Sdk\Model\ProfileReadinessChecksBody $checks Значение поля `checks`.
     *
     * @return self
     */
    public function setChecks($checks)
    {
        if (is_null($checks)) {
            throw new \InvalidArgumentException('non-nullable checks cannot be null');
        }
        $this->container['checks'] = $checks;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code Код подтверждения, ошибки или бизнес-правила.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string $label Значение поля `label`.
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets primary_action
     *
     * @return string
     */
    public function getPrimaryAction()
    {
        return $this->container['primary_action'];
    }

    /**
     * Sets primary_action
     *
     * @param string $primary_action Значение поля `primaryAction`.
     *
     * @return self
     */
    public function setPrimaryAction($primary_action)
    {
        if (is_null($primary_action)) {
            throw new \InvalidArgumentException('non-nullable primary_action cannot be null');
        }
        $allowedValues = $this->getPrimaryActionAllowableValues();
        if (!in_array($primary_action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'primary_action', must be one of '%s'",
                    $primary_action,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['primary_action'] = $primary_action;

        return $this;
    }

    /**
     * Gets tone
     *
     * @return string
     */
    public function getTone()
    {
        return $this->container['tone'];
    }

    /**
     * Sets tone
     *
     * @param string $tone Значение поля `tone`.
     *
     * @return self
     */
    public function setTone($tone)
    {
        if (is_null($tone)) {
            throw new \InvalidArgumentException('non-nullable tone cannot be null');
        }
        $allowedValues = $this->getToneAllowableValues();
        if (!in_array($tone, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tone', must be one of '%s'",
                    $tone,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tone'] = $tone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


