<?php
/**
 * ProfileResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * ProfileResponse Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProfileResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProfileResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'schema' => 'string',
        'auto_renew' => 'bool',
        'balance_after' => 'int',
        'created' => '\DateTime',
        'device_id' => 'string',
        'integration_type' => 'string',
        'is_active' => 'bool',
        'is_authorized' => 'bool',
        'name' => 'string',
        'paid_until' => '\DateTime',
        'plan_tier' => 'string',
        'price_cents' => 'int',
        'profile_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'schema' => 'uri',
        'auto_renew' => null,
        'balance_after' => 'int64',
        'created' => 'date-time',
        'device_id' => null,
        'integration_type' => null,
        'is_active' => null,
        'is_authorized' => null,
        'name' => null,
        'paid_until' => 'date-time',
        'plan_tier' => null,
        'price_cents' => 'int64',
        'profile_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'schema' => false,
        'auto_renew' => false,
        'balance_after' => false,
        'created' => false,
        'device_id' => false,
        'integration_type' => false,
        'is_active' => false,
        'is_authorized' => false,
        'name' => false,
        'paid_until' => false,
        'plan_tier' => false,
        'price_cents' => false,
        'profile_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'schema' => '$schema',
        'auto_renew' => 'autoRenew',
        'balance_after' => 'balanceAfter',
        'created' => 'created',
        'device_id' => 'deviceId',
        'integration_type' => 'integrationType',
        'is_active' => 'isActive',
        'is_authorized' => 'isAuthorized',
        'name' => 'name',
        'paid_until' => 'paidUntil',
        'plan_tier' => 'planTier',
        'price_cents' => 'priceCents',
        'profile_id' => 'profileId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'schema' => 'setSchema',
        'auto_renew' => 'setAutoRenew',
        'balance_after' => 'setBalanceAfter',
        'created' => 'setCreated',
        'device_id' => 'setDeviceId',
        'integration_type' => 'setIntegrationType',
        'is_active' => 'setIsActive',
        'is_authorized' => 'setIsAuthorized',
        'name' => 'setName',
        'paid_until' => 'setPaidUntil',
        'plan_tier' => 'setPlanTier',
        'price_cents' => 'setPriceCents',
        'profile_id' => 'setProfileId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'schema' => 'getSchema',
        'auto_renew' => 'getAutoRenew',
        'balance_after' => 'getBalanceAfter',
        'created' => 'getCreated',
        'device_id' => 'getDeviceId',
        'integration_type' => 'getIntegrationType',
        'is_active' => 'getIsActive',
        'is_authorized' => 'getIsAuthorized',
        'name' => 'getName',
        'paid_until' => 'getPaidUntil',
        'plan_tier' => 'getPlanTier',
        'price_cents' => 'getPriceCents',
        'profile_id' => 'getProfileId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('schema', $data ?? [], null);
        $this->setIfExists('auto_renew', $data ?? [], null);
        $this->setIfExists('balance_after', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('device_id', $data ?? [], null);
        $this->setIfExists('integration_type', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('is_authorized', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('paid_until', $data ?? [], null);
        $this->setIfExists('plan_tier', $data ?? [], null);
        $this->setIfExists('price_cents', $data ?? [], null);
        $this->setIfExists('profile_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['auto_renew'] === null) {
            $invalidProperties[] = "'auto_renew' can't be null";
        }
        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ($this->container['device_id'] === null) {
            $invalidProperties[] = "'device_id' can't be null";
        }
        if ($this->container['integration_type'] === null) {
            $invalidProperties[] = "'integration_type' can't be null";
        }
        if ($this->container['is_active'] === null) {
            $invalidProperties[] = "'is_active' can't be null";
        }
        if ($this->container['is_authorized'] === null) {
            $invalidProperties[] = "'is_authorized' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['paid_until'] === null) {
            $invalidProperties[] = "'paid_until' can't be null";
        }
        if ($this->container['plan_tier'] === null) {
            $invalidProperties[] = "'plan_tier' can't be null";
        }
        if ($this->container['price_cents'] === null) {
            $invalidProperties[] = "'price_cents' can't be null";
        }
        if ($this->container['profile_id'] === null) {
            $invalidProperties[] = "'profile_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets schema
     *
     * @return string|null
     */
    public function getSchema()
    {
        return $this->container['schema'];
    }

    /**
     * Sets schema
     *
     * @param string|null $schema A URL to the JSON Schema for this object.
     *
     * @return self
     */
    public function setSchema($schema)
    {
        if (is_null($schema)) {
            throw new \InvalidArgumentException('non-nullable schema cannot be null');
        }
        $this->container['schema'] = $schema;

        return $this;
    }

    /**
     * Gets auto_renew
     *
     * @return bool
     */
    public function getAutoRenew()
    {
        return $this->container['auto_renew'];
    }

    /**
     * Sets auto_renew
     *
     * @param bool $auto_renew Whether auto-renewal is enabled
     *
     * @return self
     */
    public function setAutoRenew($auto_renew)
    {
        if (is_null($auto_renew)) {
            throw new \InvalidArgumentException('non-nullable auto_renew cannot be null');
        }
        $this->container['auto_renew'] = $auto_renew;

        return $this;
    }

    /**
     * Gets balance_after
     *
     * @return int|null
     */
    public function getBalanceAfter()
    {
        return $this->container['balance_after'];
    }

    /**
     * Sets balance_after
     *
     * @param int|null $balance_after Balance after transaction (only for create/renew)
     *
     * @return self
     */
    public function setBalanceAfter($balance_after)
    {
        if (is_null($balance_after)) {
            throw new \InvalidArgumentException('non-nullable balance_after cannot be null');
        }
        $this->container['balance_after'] = $balance_after;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created Creation time
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets device_id
     *
     * @return string
     */
    public function getDeviceId()
    {
        return $this->container['device_id'];
    }

    /**
     * Sets device_id
     *
     * @param string $device_id Device identifier
     *
     * @return self
     */
    public function setDeviceId($device_id)
    {
        if (is_null($device_id)) {
            throw new \InvalidArgumentException('non-nullable device_id cannot be null');
        }
        $this->container['device_id'] = $device_id;

        return $this;
    }

    /**
     * Gets integration_type
     *
     * @return string
     */
    public function getIntegrationType()
    {
        return $this->container['integration_type'];
    }

    /**
     * Sets integration_type
     *
     * @param string $integration_type Integration type
     *
     * @return self
     */
    public function setIntegrationType($integration_type)
    {
        if (is_null($integration_type)) {
            throw new \InvalidArgumentException('non-nullable integration_type cannot be null');
        }
        $this->container['integration_type'] = $integration_type;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool $is_active Whether the profile is active
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets is_authorized
     *
     * @return bool
     */
    public function getIsAuthorized()
    {
        return $this->container['is_authorized'];
    }

    /**
     * Sets is_authorized
     *
     * @param bool $is_authorized Whether the profile is authorized in the third-party service
     *
     * @return self
     */
    public function setIsAuthorized($is_authorized)
    {
        if (is_null($is_authorized)) {
            throw new \InvalidArgumentException('non-nullable is_authorized cannot be null');
        }
        $this->container['is_authorized'] = $is_authorized;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Profile name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets paid_until
     *
     * @return \DateTime
     */
    public function getPaidUntil()
    {
        return $this->container['paid_until'];
    }

    /**
     * Sets paid_until
     *
     * @param \DateTime $paid_until Paid until time
     *
     * @return self
     */
    public function setPaidUntil($paid_until)
    {
        if (is_null($paid_until)) {
            throw new \InvalidArgumentException('non-nullable paid_until cannot be null');
        }
        $this->container['paid_until'] = $paid_until;

        return $this;
    }

    /**
     * Gets plan_tier
     *
     * @return string
     */
    public function getPlanTier()
    {
        return $this->container['plan_tier'];
    }

    /**
     * Sets plan_tier
     *
     * @param string $plan_tier Plan tier (paid, free)
     *
     * @return self
     */
    public function setPlanTier($plan_tier)
    {
        if (is_null($plan_tier)) {
            throw new \InvalidArgumentException('non-nullable plan_tier cannot be null');
        }
        $this->container['plan_tier'] = $plan_tier;

        return $this;
    }

    /**
     * Gets price_cents
     *
     * @return int
     */
    public function getPriceCents()
    {
        return $this->container['price_cents'];
    }

    /**
     * Sets price_cents
     *
     * @param int $price_cents Renewal price in cents
     *
     * @return self
     */
    public function setPriceCents($price_cents)
    {
        if (is_null($price_cents)) {
            throw new \InvalidArgumentException('non-nullable price_cents cannot be null');
        }
        $this->container['price_cents'] = $price_cents;

        return $this;
    }

    /**
     * Gets profile_id
     *
     * @return string
     */
    public function getProfileId()
    {
        return $this->container['profile_id'];
    }

    /**
     * Sets profile_id
     *
     * @param string $profile_id Unique profile identifier
     *
     * @return self
     */
    public function setProfileId($profile_id)
    {
        if (is_null($profile_id)) {
            throw new \InvalidArgumentException('non-nullable profile_id cannot be null');
        }
        $this->container['profile_id'] = $profile_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


