<?php
/**
 * ProfileRenewOutputBody
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya Public API (SDK)
 *
 * Public customer API for Relaya SDKs. Authenticated with a profile API token (`X-Profile-Token`). Staff Admin API is intentionally excluded from this contract. Scopes: profiles:read|write, inbox:read|write, webhooks:manage, billing:read|write. Профили, сообщения, инбокс, модули, вебхуки и биллинг.
 *
 * The version of the OpenAPI document: devel
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * ProfileRenewOutputBody Class Doc Comment
 *
 * @category Class
 * @description JSON-модель успешного ответа.
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProfileRenewOutputBody implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProfileRenewOutputBody';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'schema' => 'string',
        'applied_promotion' => '\Relaya\Sdk\Model\AppliedPromotionSummary',
        'auto_renew' => 'bool',
        'balance_after' => 'int',
        'base_amount_cents' => 'int',
        'discount_amount_cents' => 'int',
        'final_amount_cents' => 'int',
        'is_active' => 'bool',
        'paid_until' => '\DateTime',
        'price_cents' => 'int',
        'profile_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'schema' => 'uri',
        'applied_promotion' => null,
        'auto_renew' => null,
        'balance_after' => 'int64',
        'base_amount_cents' => 'int64',
        'discount_amount_cents' => 'int64',
        'final_amount_cents' => 'int64',
        'is_active' => null,
        'paid_until' => 'date-time',
        'price_cents' => 'int64',
        'profile_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'schema' => false,
        'applied_promotion' => false,
        'auto_renew' => false,
        'balance_after' => false,
        'base_amount_cents' => false,
        'discount_amount_cents' => false,
        'final_amount_cents' => false,
        'is_active' => false,
        'paid_until' => false,
        'price_cents' => false,
        'profile_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'schema' => '$schema',
        'applied_promotion' => 'appliedPromotion',
        'auto_renew' => 'autoRenew',
        'balance_after' => 'balanceAfter',
        'base_amount_cents' => 'baseAmountCents',
        'discount_amount_cents' => 'discountAmountCents',
        'final_amount_cents' => 'finalAmountCents',
        'is_active' => 'isActive',
        'paid_until' => 'paidUntil',
        'price_cents' => 'priceCents',
        'profile_id' => 'profileId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'schema' => 'setSchema',
        'applied_promotion' => 'setAppliedPromotion',
        'auto_renew' => 'setAutoRenew',
        'balance_after' => 'setBalanceAfter',
        'base_amount_cents' => 'setBaseAmountCents',
        'discount_amount_cents' => 'setDiscountAmountCents',
        'final_amount_cents' => 'setFinalAmountCents',
        'is_active' => 'setIsActive',
        'paid_until' => 'setPaidUntil',
        'price_cents' => 'setPriceCents',
        'profile_id' => 'setProfileId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'schema' => 'getSchema',
        'applied_promotion' => 'getAppliedPromotion',
        'auto_renew' => 'getAutoRenew',
        'balance_after' => 'getBalanceAfter',
        'base_amount_cents' => 'getBaseAmountCents',
        'discount_amount_cents' => 'getDiscountAmountCents',
        'final_amount_cents' => 'getFinalAmountCents',
        'is_active' => 'getIsActive',
        'paid_until' => 'getPaidUntil',
        'price_cents' => 'getPriceCents',
        'profile_id' => 'getProfileId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('schema', $data ?? [], null);
        $this->setIfExists('applied_promotion', $data ?? [], null);
        $this->setIfExists('auto_renew', $data ?? [], null);
        $this->setIfExists('balance_after', $data ?? [], null);
        $this->setIfExists('base_amount_cents', $data ?? [], null);
        $this->setIfExists('discount_amount_cents', $data ?? [], null);
        $this->setIfExists('final_amount_cents', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('paid_until', $data ?? [], null);
        $this->setIfExists('price_cents', $data ?? [], null);
        $this->setIfExists('profile_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['auto_renew'] === null) {
            $invalidProperties[] = "'auto_renew' can't be null";
        }
        if ($this->container['is_active'] === null) {
            $invalidProperties[] = "'is_active' can't be null";
        }
        if ($this->container['paid_until'] === null) {
            $invalidProperties[] = "'paid_until' can't be null";
        }
        if ($this->container['price_cents'] === null) {
            $invalidProperties[] = "'price_cents' can't be null";
        }
        if ($this->container['profile_id'] === null) {
            $invalidProperties[] = "'profile_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets schema
     *
     * @return string|null
     */
    public function getSchema()
    {
        return $this->container['schema'];
    }

    /**
     * Sets schema
     *
     * @param string|null $schema Ссылка на JSON Schema этой модели.
     *
     * @return self
     */
    public function setSchema($schema)
    {
        if (is_null($schema)) {
            throw new \InvalidArgumentException('non-nullable schema cannot be null');
        }
        $this->container['schema'] = $schema;

        return $this;
    }

    /**
     * Gets applied_promotion
     *
     * @return \Relaya\Sdk\Model\AppliedPromotionSummary|null
     */
    public function getAppliedPromotion()
    {
        return $this->container['applied_promotion'];
    }

    /**
     * Sets applied_promotion
     *
     * @param \Relaya\Sdk\Model\AppliedPromotionSummary|null $applied_promotion Сведения о примененной акции или промокоде.
     *
     * @return self
     */
    public function setAppliedPromotion($applied_promotion)
    {
        if (is_null($applied_promotion)) {
            throw new \InvalidArgumentException('non-nullable applied_promotion cannot be null');
        }
        $this->container['applied_promotion'] = $applied_promotion;

        return $this;
    }

    /**
     * Gets auto_renew
     *
     * @return bool
     */
    public function getAutoRenew()
    {
        return $this->container['auto_renew'];
    }

    /**
     * Sets auto_renew
     *
     * @param bool $auto_renew Показывает, включено ли автопродление.
     *
     * @return self
     */
    public function setAutoRenew($auto_renew)
    {
        if (is_null($auto_renew)) {
            throw new \InvalidArgumentException('non-nullable auto_renew cannot be null');
        }
        $this->container['auto_renew'] = $auto_renew;

        return $this;
    }

    /**
     * Gets balance_after
     *
     * @return int|null
     */
    public function getBalanceAfter()
    {
        return $this->container['balance_after'];
    }

    /**
     * Sets balance_after
     *
     * @param int|null $balance_after Баланс после выполнения операции.
     *
     * @return self
     */
    public function setBalanceAfter($balance_after)
    {
        if (is_null($balance_after)) {
            throw new \InvalidArgumentException('non-nullable balance_after cannot be null');
        }
        $this->container['balance_after'] = $balance_after;

        return $this;
    }

    /**
     * Gets base_amount_cents
     *
     * @return int|null
     */
    public function getBaseAmountCents()
    {
        return $this->container['base_amount_cents'];
    }

    /**
     * Sets base_amount_cents
     *
     * @param int|null $base_amount_cents Базовая сумма до скидок в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setBaseAmountCents($base_amount_cents)
    {
        if (is_null($base_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable base_amount_cents cannot be null');
        }
        $this->container['base_amount_cents'] = $base_amount_cents;

        return $this;
    }

    /**
     * Gets discount_amount_cents
     *
     * @return int|null
     */
    public function getDiscountAmountCents()
    {
        return $this->container['discount_amount_cents'];
    }

    /**
     * Sets discount_amount_cents
     *
     * @param int|null $discount_amount_cents Размер скидки в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setDiscountAmountCents($discount_amount_cents)
    {
        if (is_null($discount_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable discount_amount_cents cannot be null');
        }
        $this->container['discount_amount_cents'] = $discount_amount_cents;

        return $this;
    }

    /**
     * Gets final_amount_cents
     *
     * @return int|null
     */
    public function getFinalAmountCents()
    {
        return $this->container['final_amount_cents'];
    }

    /**
     * Sets final_amount_cents
     *
     * @param int|null $final_amount_cents Итоговая сумма к оплате в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setFinalAmountCents($final_amount_cents)
    {
        if (is_null($final_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable final_amount_cents cannot be null');
        }
        $this->container['final_amount_cents'] = $final_amount_cents;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool $is_active Показывает, активна ли сущность.
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets paid_until
     *
     * @return \DateTime
     */
    public function getPaidUntil()
    {
        return $this->container['paid_until'];
    }

    /**
     * Sets paid_until
     *
     * @param \DateTime $paid_until Дата, до которой профиль или модуль оплачен.
     *
     * @return self
     */
    public function setPaidUntil($paid_until)
    {
        if (is_null($paid_until)) {
            throw new \InvalidArgumentException('non-nullable paid_until cannot be null');
        }
        $this->container['paid_until'] = $paid_until;

        return $this;
    }

    /**
     * Gets price_cents
     *
     * @return int
     */
    public function getPriceCents()
    {
        return $this->container['price_cents'];
    }

    /**
     * Sets price_cents
     *
     * @param int $price_cents Цена в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setPriceCents($price_cents)
    {
        if (is_null($price_cents)) {
            throw new \InvalidArgumentException('non-nullable price_cents cannot be null');
        }
        $this->container['price_cents'] = $price_cents;

        return $this;
    }

    /**
     * Gets profile_id
     *
     * @return string
     */
    public function getProfileId()
    {
        return $this->container['profile_id'];
    }

    /**
     * Sets profile_id
     *
     * @param string $profile_id Идентификатор профиля Релая. Для новых профилей это 12-символьная hex-строка.
     *
     * @return self
     */
    public function setProfileId($profile_id)
    {
        if (is_null($profile_id)) {
            throw new \InvalidArgumentException('non-nullable profile_id cannot be null');
        }
        $this->container['profile_id'] = $profile_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


