<?php
/**
 * ProfilesListSummaryBodyReadinessStruct
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya Public API (SDK)
 *
 * Public customer API for Relaya SDKs. Authenticated with a profile API token (`X-Profile-Token`). Staff Admin API is intentionally excluded from this contract. Scopes: profiles:read|write, inbox:read|write, webhooks:manage, billing:read|write. Профили, сообщения, инбокс, модули, вебхуки и биллинг.
 *
 * The version of the OpenAPI document: devel
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * ProfilesListSummaryBodyReadinessStruct Class Doc Comment
 *
 * @category Class
 * @description Объект модели API.
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProfilesListSummaryBodyReadinessStruct implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProfilesListSummaryBodyReadinessStruct';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'inbox_only' => 'int',
        'needs_auth' => 'int',
        'needs_payment' => 'int',
        'needs_webhook' => 'int',
        'ready' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'inbox_only' => 'int64',
        'needs_auth' => 'int64',
        'needs_payment' => 'int64',
        'needs_webhook' => 'int64',
        'ready' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'inbox_only' => false,
        'needs_auth' => false,
        'needs_payment' => false,
        'needs_webhook' => false,
        'ready' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'inbox_only' => 'inboxOnly',
        'needs_auth' => 'needsAuth',
        'needs_payment' => 'needsPayment',
        'needs_webhook' => 'needsWebhook',
        'ready' => 'ready'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'inbox_only' => 'setInboxOnly',
        'needs_auth' => 'setNeedsAuth',
        'needs_payment' => 'setNeedsPayment',
        'needs_webhook' => 'setNeedsWebhook',
        'ready' => 'setReady'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'inbox_only' => 'getInboxOnly',
        'needs_auth' => 'getNeedsAuth',
        'needs_payment' => 'getNeedsPayment',
        'needs_webhook' => 'getNeedsWebhook',
        'ready' => 'getReady'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('inbox_only', $data ?? [], null);
        $this->setIfExists('needs_auth', $data ?? [], null);
        $this->setIfExists('needs_payment', $data ?? [], null);
        $this->setIfExists('needs_webhook', $data ?? [], null);
        $this->setIfExists('ready', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['inbox_only'] === null) {
            $invalidProperties[] = "'inbox_only' can't be null";
        }
        if ($this->container['needs_auth'] === null) {
            $invalidProperties[] = "'needs_auth' can't be null";
        }
        if ($this->container['needs_payment'] === null) {
            $invalidProperties[] = "'needs_payment' can't be null";
        }
        if ($this->container['needs_webhook'] === null) {
            $invalidProperties[] = "'needs_webhook' can't be null";
        }
        if ($this->container['ready'] === null) {
            $invalidProperties[] = "'ready' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets inbox_only
     *
     * @return int
     */
    public function getInboxOnly()
    {
        return $this->container['inbox_only'];
    }

    /**
     * Sets inbox_only
     *
     * @param int $inbox_only Значение поля `inboxOnly`.
     *
     * @return self
     */
    public function setInboxOnly($inbox_only)
    {
        if (is_null($inbox_only)) {
            throw new \InvalidArgumentException('non-nullable inbox_only cannot be null');
        }
        $this->container['inbox_only'] = $inbox_only;

        return $this;
    }

    /**
     * Gets needs_auth
     *
     * @return int
     */
    public function getNeedsAuth()
    {
        return $this->container['needs_auth'];
    }

    /**
     * Sets needs_auth
     *
     * @param int $needs_auth Значение поля `needsAuth`.
     *
     * @return self
     */
    public function setNeedsAuth($needs_auth)
    {
        if (is_null($needs_auth)) {
            throw new \InvalidArgumentException('non-nullable needs_auth cannot be null');
        }
        $this->container['needs_auth'] = $needs_auth;

        return $this;
    }

    /**
     * Gets needs_payment
     *
     * @return int
     */
    public function getNeedsPayment()
    {
        return $this->container['needs_payment'];
    }

    /**
     * Sets needs_payment
     *
     * @param int $needs_payment Значение поля `needsPayment`.
     *
     * @return self
     */
    public function setNeedsPayment($needs_payment)
    {
        if (is_null($needs_payment)) {
            throw new \InvalidArgumentException('non-nullable needs_payment cannot be null');
        }
        $this->container['needs_payment'] = $needs_payment;

        return $this;
    }

    /**
     * Gets needs_webhook
     *
     * @return int
     */
    public function getNeedsWebhook()
    {
        return $this->container['needs_webhook'];
    }

    /**
     * Sets needs_webhook
     *
     * @param int $needs_webhook Значение поля `needsWebhook`.
     *
     * @return self
     */
    public function setNeedsWebhook($needs_webhook)
    {
        if (is_null($needs_webhook)) {
            throw new \InvalidArgumentException('non-nullable needs_webhook cannot be null');
        }
        $this->container['needs_webhook'] = $needs_webhook;

        return $this;
    }

    /**
     * Gets ready
     *
     * @return int
     */
    public function getReady()
    {
        return $this->container['ready'];
    }

    /**
     * Sets ready
     *
     * @param int $ready Значение поля `ready`.
     *
     * @return self
     */
    public function setReady($ready)
    {
        if (is_null($ready)) {
            throw new \InvalidArgumentException('non-nullable ready cannot be null');
        }
        $this->container['ready'] = $ready;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


