<?php
/**
 * TopUpStatusResponseItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya Public API (SDK)
 *
 * Public customer API for Relaya SDKs. Authenticated with a profile API token (`X-Profile-Token`). Staff Admin API is intentionally excluded from this contract. Scopes: profiles:read|write, inbox:read|write, webhooks:manage, billing:read|write. Профили, сообщения, инбокс, модули, вебхуки и биллинг.
 *
 * The version of the OpenAPI document: devel
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Relaya\Sdk\Model;

use \ArrayAccess;
use \Relaya\Sdk\ObjectSerializer;

/**
 * TopUpStatusResponseItem Class Doc Comment
 *
 * @category Class
 * @description JSON-модель успешного ответа.
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TopUpStatusResponseItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TopUpStatusResponseItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amount_cents' => 'int',
        'applied_promotion' => '\Relaya\Sdk\Model\AppliedPromotionSummary',
        'base_amount_cents' => 'int',
        'bonus_amount_cents' => 'int',
        'confirmed_at' => '\DateTime',
        'created_at' => '\DateTime',
        'currency' => 'string',
        'discount_amount_cents' => 'int',
        'error_message' => 'string',
        'expires_at' => '\DateTime',
        'final_amount_cents' => 'int',
        'payment_url' => 'string',
        'provider' => 'string',
        'provider_payment_id' => 'string',
        'status' => 'string',
        'topup_id' => 'string',
        'updated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amount_cents' => 'int64',
        'applied_promotion' => null,
        'base_amount_cents' => 'int64',
        'bonus_amount_cents' => 'int64',
        'confirmed_at' => 'date-time',
        'created_at' => 'date-time',
        'currency' => null,
        'discount_amount_cents' => 'int64',
        'error_message' => null,
        'expires_at' => 'date-time',
        'final_amount_cents' => 'int64',
        'payment_url' => null,
        'provider' => null,
        'provider_payment_id' => null,
        'status' => null,
        'topup_id' => null,
        'updated_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'amount_cents' => false,
        'applied_promotion' => false,
        'base_amount_cents' => false,
        'bonus_amount_cents' => false,
        'confirmed_at' => false,
        'created_at' => false,
        'currency' => false,
        'discount_amount_cents' => false,
        'error_message' => false,
        'expires_at' => false,
        'final_amount_cents' => false,
        'payment_url' => false,
        'provider' => false,
        'provider_payment_id' => false,
        'status' => false,
        'topup_id' => false,
        'updated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount_cents' => 'amountCents',
        'applied_promotion' => 'appliedPromotion',
        'base_amount_cents' => 'baseAmountCents',
        'bonus_amount_cents' => 'bonusAmountCents',
        'confirmed_at' => 'confirmedAt',
        'created_at' => 'createdAt',
        'currency' => 'currency',
        'discount_amount_cents' => 'discountAmountCents',
        'error_message' => 'errorMessage',
        'expires_at' => 'expiresAt',
        'final_amount_cents' => 'finalAmountCents',
        'payment_url' => 'paymentUrl',
        'provider' => 'provider',
        'provider_payment_id' => 'providerPaymentId',
        'status' => 'status',
        'topup_id' => 'topupId',
        'updated_at' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount_cents' => 'setAmountCents',
        'applied_promotion' => 'setAppliedPromotion',
        'base_amount_cents' => 'setBaseAmountCents',
        'bonus_amount_cents' => 'setBonusAmountCents',
        'confirmed_at' => 'setConfirmedAt',
        'created_at' => 'setCreatedAt',
        'currency' => 'setCurrency',
        'discount_amount_cents' => 'setDiscountAmountCents',
        'error_message' => 'setErrorMessage',
        'expires_at' => 'setExpiresAt',
        'final_amount_cents' => 'setFinalAmountCents',
        'payment_url' => 'setPaymentUrl',
        'provider' => 'setProvider',
        'provider_payment_id' => 'setProviderPaymentId',
        'status' => 'setStatus',
        'topup_id' => 'setTopupId',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount_cents' => 'getAmountCents',
        'applied_promotion' => 'getAppliedPromotion',
        'base_amount_cents' => 'getBaseAmountCents',
        'bonus_amount_cents' => 'getBonusAmountCents',
        'confirmed_at' => 'getConfirmedAt',
        'created_at' => 'getCreatedAt',
        'currency' => 'getCurrency',
        'discount_amount_cents' => 'getDiscountAmountCents',
        'error_message' => 'getErrorMessage',
        'expires_at' => 'getExpiresAt',
        'final_amount_cents' => 'getFinalAmountCents',
        'payment_url' => 'getPaymentUrl',
        'provider' => 'getProvider',
        'provider_payment_id' => 'getProviderPaymentId',
        'status' => 'getStatus',
        'topup_id' => 'getTopupId',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amount_cents', $data ?? [], null);
        $this->setIfExists('applied_promotion', $data ?? [], null);
        $this->setIfExists('base_amount_cents', $data ?? [], null);
        $this->setIfExists('bonus_amount_cents', $data ?? [], null);
        $this->setIfExists('confirmed_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('discount_amount_cents', $data ?? [], null);
        $this->setIfExists('error_message', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('final_amount_cents', $data ?? [], null);
        $this->setIfExists('payment_url', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('provider_payment_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('topup_id', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount_cents'] === null) {
            $invalidProperties[] = "'amount_cents' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['provider'] === null) {
            $invalidProperties[] = "'provider' can't be null";
        }
        if ($this->container['provider_payment_id'] === null) {
            $invalidProperties[] = "'provider_payment_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['topup_id'] === null) {
            $invalidProperties[] = "'topup_id' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount_cents
     *
     * @return int
     */
    public function getAmountCents()
    {
        return $this->container['amount_cents'];
    }

    /**
     * Sets amount_cents
     *
     * @param int $amount_cents Сумма в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setAmountCents($amount_cents)
    {
        if (is_null($amount_cents)) {
            throw new \InvalidArgumentException('non-nullable amount_cents cannot be null');
        }
        $this->container['amount_cents'] = $amount_cents;

        return $this;
    }

    /**
     * Gets applied_promotion
     *
     * @return \Relaya\Sdk\Model\AppliedPromotionSummary|null
     */
    public function getAppliedPromotion()
    {
        return $this->container['applied_promotion'];
    }

    /**
     * Sets applied_promotion
     *
     * @param \Relaya\Sdk\Model\AppliedPromotionSummary|null $applied_promotion Сведения о примененной акции или промокоде.
     *
     * @return self
     */
    public function setAppliedPromotion($applied_promotion)
    {
        if (is_null($applied_promotion)) {
            throw new \InvalidArgumentException('non-nullable applied_promotion cannot be null');
        }
        $this->container['applied_promotion'] = $applied_promotion;

        return $this;
    }

    /**
     * Gets base_amount_cents
     *
     * @return int|null
     */
    public function getBaseAmountCents()
    {
        return $this->container['base_amount_cents'];
    }

    /**
     * Sets base_amount_cents
     *
     * @param int|null $base_amount_cents Базовая сумма до скидок в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setBaseAmountCents($base_amount_cents)
    {
        if (is_null($base_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable base_amount_cents cannot be null');
        }
        $this->container['base_amount_cents'] = $base_amount_cents;

        return $this;
    }

    /**
     * Gets bonus_amount_cents
     *
     * @return int|null
     */
    public function getBonusAmountCents()
    {
        return $this->container['bonus_amount_cents'];
    }

    /**
     * Sets bonus_amount_cents
     *
     * @param int|null $bonus_amount_cents Сумма бонуса в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setBonusAmountCents($bonus_amount_cents)
    {
        if (is_null($bonus_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable bonus_amount_cents cannot be null');
        }
        $this->container['bonus_amount_cents'] = $bonus_amount_cents;

        return $this;
    }

    /**
     * Gets confirmed_at
     *
     * @return \DateTime|null
     */
    public function getConfirmedAt()
    {
        return $this->container['confirmed_at'];
    }

    /**
     * Sets confirmed_at
     *
     * @param \DateTime|null $confirmed_at Время подтверждения операции в UTC.
     *
     * @return self
     */
    public function setConfirmedAt($confirmed_at)
    {
        if (is_null($confirmed_at)) {
            throw new \InvalidArgumentException('non-nullable confirmed_at cannot be null');
        }
        $this->container['confirmed_at'] = $confirmed_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Время создания сущности в UTC.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency Код валюты в формате ISO 4217.
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets discount_amount_cents
     *
     * @return int|null
     */
    public function getDiscountAmountCents()
    {
        return $this->container['discount_amount_cents'];
    }

    /**
     * Sets discount_amount_cents
     *
     * @param int|null $discount_amount_cents Размер скидки в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setDiscountAmountCents($discount_amount_cents)
    {
        if (is_null($discount_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable discount_amount_cents cannot be null');
        }
        $this->container['discount_amount_cents'] = $discount_amount_cents;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string|null
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string|null $error_message Текст ошибки от внешнего провайдера или внутреннего обработчика.
     *
     * @return self
     */
    public function setErrorMessage($error_message)
    {
        if (is_null($error_message)) {
            throw new \InvalidArgumentException('non-nullable error_message cannot be null');
        }
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at Время, после которого значение или процесс перестает быть актуальным.
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            throw new \InvalidArgumentException('non-nullable expires_at cannot be null');
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets final_amount_cents
     *
     * @return int|null
     */
    public function getFinalAmountCents()
    {
        return $this->container['final_amount_cents'];
    }

    /**
     * Sets final_amount_cents
     *
     * @param int|null $final_amount_cents Итоговая сумма к оплате в копейках или минимальных единицах валюты.
     *
     * @return self
     */
    public function setFinalAmountCents($final_amount_cents)
    {
        if (is_null($final_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable final_amount_cents cannot be null');
        }
        $this->container['final_amount_cents'] = $final_amount_cents;

        return $this;
    }

    /**
     * Gets payment_url
     *
     * @return string|null
     */
    public function getPaymentUrl()
    {
        return $this->container['payment_url'];
    }

    /**
     * Sets payment_url
     *
     * @param string|null $payment_url Ссылка на страницу оплаты у провайдера.
     *
     * @return self
     */
    public function setPaymentUrl($payment_url)
    {
        if (is_null($payment_url)) {
            throw new \InvalidArgumentException('non-nullable payment_url cannot be null');
        }
        $this->container['payment_url'] = $payment_url;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return string
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param string $provider Код внешнего провайдера.
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            throw new \InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets provider_payment_id
     *
     * @return string
     */
    public function getProviderPaymentId()
    {
        return $this->container['provider_payment_id'];
    }

    /**
     * Sets provider_payment_id
     *
     * @param string $provider_payment_id Идентификатор записи или внешнего ресурса.
     *
     * @return self
     */
    public function setProviderPaymentId($provider_payment_id)
    {
        if (is_null($provider_payment_id)) {
            throw new \InvalidArgumentException('non-nullable provider_payment_id cannot be null');
        }
        $this->container['provider_payment_id'] = $provider_payment_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Текущий статус сущности.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets topup_id
     *
     * @return string
     */
    public function getTopupId()
    {
        return $this->container['topup_id'];
    }

    /**
     * Sets topup_id
     *
     * @param string $topup_id Идентификатор записи или внешнего ресурса.
     *
     * @return self
     */
    public function setTopupId($topup_id)
    {
        if (is_null($topup_id)) {
            throw new \InvalidArgumentException('non-nullable topup_id cannot be null');
        }
        $this->container['topup_id'] = $topup_id;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at Время последнего обновления в UTC.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


