<?php
/**
 * MaxUserSettingsPatchTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Relaya\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MaxUserSettingsPatchTest Class Doc Comment
 *
 * @category    Class
 * @description MaxUserSettingsPatch
 * @package     Relaya\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MaxUserSettingsPatchTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MaxUserSettingsPatch"
     */
    public function testMaxUserSettingsPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alt_keyboard"
     */
    public function testPropertyAltKeyboard()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "audio_transcription_enabled"
     */
    public function testPropertyAudioTranscriptionEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "chats_invite"
     */
    public function testPropertyChatsInvite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "chats_push_notification"
     */
    public function testPropertyChatsPushNotification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "chats_push_sound"
     */
    public function testPropertyChatsPushSound()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_level_access"
     */
    public function testPropertyContentLevelAccess()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dont_disturb_until"
     */
    public function testPropertyDontDisturbUntil()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "double_tap_reaction_disabled"
     */
    public function testPropertyDoubleTapReactionDisabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "family_protection"
     */
    public function testPropertyFamilyProtection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hidden"
     */
    public function testPropertyHidden()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inactive_ttl"
     */
    public function testPropertyInactiveTtl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "incoming_call"
     */
    public function testPropertyIncomingCall()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "m_call_push_notification"
     */
    public function testPropertyMCallPushNotification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push_details"
     */
    public function testPropertyPushDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push_new_contacts"
     */
    public function testPropertyPushNewContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push_sound"
     */
    public function testPropertyPushSound()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "safe_mode"
     */
    public function testPropertySafeMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "safe_mode_no_pin"
     */
    public function testPropertySafeModeNoPin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "search_by_phone"
     */
    public function testPropertySearchByPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "show_read_mark"
     */
    public function testPropertyShowReadMark()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stickers_suggest"
     */
    public function testPropertyStickersSuggest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unsafe_files"
     */
    public function testPropertyUnsafeFiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
