<?php
/**
 * UserInboxConversationMetaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Relaya\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UserInboxConversationMetaTest Class Doc Comment
 *
 * @category    Class
 * @description UserInboxConversationMeta
 * @package     Relaya\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserInboxConversationMetaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserInboxConversationMeta"
     */
    public function testUserInboxConversationMeta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avatar_url"
     */
    public function testPropertyAvatarUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "muted"
     */
    public function testPropertyMuted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "starred"
     */
    public function testPropertyStarred()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
