<?php
/**
 * BillingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya Public API (SDK)
 *
 * Public customer API for Relaya SDKs. Authenticated with a profile API token (`X-Profile-Token`). Staff Admin API is intentionally excluded from this contract. Scopes: profiles:read|write, inbox:read|write, webhooks:manage, billing:read|write. Профили, сообщения, инбокс, модули, вебхуки и биллинг.
 *
 * The version of the OpenAPI document: devel
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Relaya\Sdk\Test\Api;

use \Relaya\Sdk\Configuration;
use \Relaya\Sdk\ApiException;
use \Relaya\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BillingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BillingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getBillingCompanyLookup
     *
     * Подсказки по организации.
     *
     */
    public function testGetBillingCompanyLookup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingInvoice
     *
     * Карточка счёта.
     *
     */
    public function testGetBillingInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingInvoices
     *
     * Список счетов.
     *
     */
    public function testGetBillingInvoices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingInvoicesInvoiceIdAct
     *
     * Скачать акт по счёту.
     *
     */
    public function testGetBillingInvoicesInvoiceIdAct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingLegalProfile
     *
     * Юридический профиль.
     *
     */
    public function testGetBillingLegalProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingTopups
     *
     * Пополнения.
     *
     */
    public function testGetBillingTopups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingTopupsTopupId
     *
     * Статус пополнения.
     *
     */
    public function testGetBillingTopupsTopupId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBillingTransactions
     *
     * Транзакции.
     *
     */
    public function testGetBillingTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBillingInvoiceRefresh
     *
     * Обновить статус счёта.
     *
     */
    public function testPostBillingInvoiceRefresh()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBillingInvoices
     *
     * Выставить счёт.
     *
     */
    public function testPostBillingInvoices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBillingTopups
     *
     * Создать пополнение.
     *
     */
    public function testPostBillingTopups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBillingTopupsTopupIdRefresh
     *
     * Обновить статус пополнения.
     *
     */
    public function testPostBillingTopupsTopupIdRefresh()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putBillingLegalProfile
     *
     * Сохранить юридический профиль.
     *
     */
    public function testPutBillingLegalProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
