<?php
/**
 * MaxApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Relaya\Sdk\Test\Api;

use \Relaya\Sdk\Configuration;
use \Relaya\Sdk\ApiException;
use \Relaya\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MaxApiTest Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MaxApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteProfilesProfileIdIntegrationsIntegrationFoldersFolderId
     *
     * Delete MAX folder.
     *
     */
    public function testDeleteProfilesProfileIdIntegrationsIntegrationFoldersFolderId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProfilesProfileIdIntegrationsIntegrationMessagesReactions
     *
     * Remove reaction.
     *
     */
    public function testDeleteProfilesProfileIdIntegrationsIntegrationMessagesReactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationContacts
     *
     * List contacts.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationContactsBlocked
     *
     * List blocked contacts.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationContactsBlocked()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationDevices
     *
     * List active MAX devices.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationDevices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationFolders
     *
     * List MAX folders.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationSessions
     *
     * List active MAX sessions/devices.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationSessions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationSettings
     *
     * Get settings.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationSettingsUser
     *
     * Get MAX account settings.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationSettingsUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileIdIntegrationsIntegrationAccountProfile
     *
     * Update MAX profile name/description.
     *
     */
    public function testPatchProfilesProfileIdIntegrationsIntegrationAccountProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileIdIntegrationsIntegrationSettings
     *
     * Update settings.
     *
     */
    public function testPatchProfilesProfileIdIntegrationsIntegrationSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileIdIntegrationsIntegrationSettingsUser
     *
     * Update MAX account settings.
     *
     */
    public function testPatchProfilesProfileIdIntegrationsIntegrationSettingsUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationAuthSmsPoll
     *
     * Poll authorization.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationAuthSmsPoll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationAuthSmsStart
     *
     * Start SMS authorization.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationAuthSmsStart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationAuthSmsVerify
     *
     * Send authorization code.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationAuthSmsVerify()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationChatsByIds
     *
     * Get chats by IDs.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationChatsByIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationChatsSubscription
     *
     * Subscribe/unsubscribe chat updates.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationChatsSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationContactsByIds
     *
     * Get contacts by IDs.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationContactsByIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationContactsLastOnline
     *
     * Get contacts last online by IDs.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationContactsLastOnline()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationContactsSearch
     *
     * Search contact by phone.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationContactsSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationFolders
     *
     * Create MAX folder.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationMessagesReactions
     *
     * Send reaction.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationMessagesReactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationMessagesRead
     *
     * Mark chat read.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationMessagesRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationMessagesTyping
     *
     * Send typing status.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationMessagesTyping()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationMessagesUnread
     *
     * Mark chat as unread.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationMessagesUnread()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationReboot
     *
     * Reboot profile.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationReboot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationVideosResolve
     *
     * Resolve video links by video ID.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationVideosResolve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationAvatarPost
     *
     * Set profile picture.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationAvatarPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putProfilesProfileIdIntegrationsIntegrationFoldersOrder
     *
     * Reorder MAX folders.
     *
     */
    public function testPutProfilesProfileIdIntegrationsIntegrationFoldersOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
