<?php
/**
 * ProfilesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Relaya\Sdk\Test\Api;

use \Relaya\Sdk\Configuration;
use \Relaya\Sdk\ApiException;
use \Relaya\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProfilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteProfilesProfileId
     *
     * Delete profile.
     *
     */
    public function testDeleteProfilesProfileId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfiles
     *
     * List profiles.
     *
     */
    public function testGetProfiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileId
     *
     * Get profile.
     *
     */
    public function testGetProfilesProfileId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdActions
     *
     * Get profile actions.
     *
     */
    public function testGetProfilesProfileIdActions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationContacts
     *
     * List contacts.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationContactsBlocked
     *
     * List blocked contacts.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationContactsBlocked()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationOverview
     *
     * Get profile overview.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationOverview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationStatus
     *
     * Get profile status.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileId
     *
     * Update profile.
     *
     */
    public function testPatchProfilesProfileId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileIdIntegrationsIntegrationAccountProfile
     *
     * Update MAX profile name/description.
     *
     */
    public function testPatchProfilesProfileIdIntegrationsIntegrationAccountProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfiles
     *
     * Create profile.
     *
     */
    public function testPostProfiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationContactsByIds
     *
     * Get contacts by IDs.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationContactsByIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationContactsLastOnline
     *
     * Get contacts last online by IDs.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationContactsLastOnline()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationContactsSearch
     *
     * Search contact by phone.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationContactsSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationReboot
     *
     * Reboot profile.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationReboot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdRenew
     *
     * Renew profile.
     *
     */
    public function testPostProfilesProfileIdRenew()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationAvatarPost
     *
     * Set profile picture.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationAvatarPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putProfilesProfileIdAutoRenew
     *
     * Update auto-renew.
     *
     */
    public function testPutProfilesProfileIdAutoRenew()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
