<?php
/**
 * SettingsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Relaya\Sdk\Test\Api;

use \Relaya\Sdk\Configuration;
use \Relaya\Sdk\ApiException;
use \Relaya\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SettingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationSettings
     *
     * Get settings.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationSettingsUser
     *
     * Get MAX account settings.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationSettingsUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileIdIntegrationsIntegrationSettings
     *
     * Update settings.
     *
     */
    public function testPatchProfilesProfileIdIntegrationsIntegrationSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileIdIntegrationsIntegrationSettingsUser
     *
     * Update MAX account settings.
     *
     */
    public function testPatchProfilesProfileIdIntegrationsIntegrationSettingsUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
