<?php
/**
 * WebhooksApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya
 *
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Relaya\Sdk\Test\Api;

use \Relaya\Sdk\Configuration;
use \Relaya\Sdk\ApiException;
use \Relaya\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksCheckPost
     *
     * Check webhook endpoint.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksCheckPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksDlqGet
     *
     * List webhook DLQ.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksDlqGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksDlqRedrivePost
     *
     * Redrive webhook DLQ.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksDlqRedrivePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksGet
     *
     * List webhooks.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksIdDelete
     *
     * Delete webhook.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksIdGet
     *
     * Get webhook.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksIdPatch
     *
     * Update webhook.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksIdTestPost
     *
     * Test webhook.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksIdTestPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for profilesProfileIdIntegrationsIntegrationWebhooksPost
     *
     * Create webhook.
     *
     */
    public function testProfilesProfileIdIntegrationsIntegrationWebhooksPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
