<?php
/**
 * WebhooksApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Relaya Public API (SDK)
 *
 * Public customer API for Relaya SDKs. Authenticated with a profile API token (`X-Profile-Token`). Staff Admin API is intentionally excluded from this contract. Scopes: profiles:read|write, inbox:read|write, webhooks:manage, billing:read|write. Профили, сообщения, инбокс, модули, вебхуки и биллинг.
 *
 * The version of the OpenAPI document: devel
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Relaya\Sdk\Test\Api;

use \Relaya\Sdk\Configuration;
use \Relaya\Sdk\ApiException;
use \Relaya\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Relaya\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteProfilesProfileIdIntegrationsIntegrationWebhook
     *
     * Отключить входящий webhook интеграции.
     *
     */
    public function testDeleteProfilesProfileIdIntegrationsIntegrationWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProfilesProfileIdIntegrationsIntegrationWebhooksId
     *
     * Удалить вебхук.
     *
     */
    public function testDeleteProfilesProfileIdIntegrationsIntegrationWebhooksId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationWebhook
     *
     * Получить входящий webhook интеграции.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationWebhooks
     *
     * Получить список вебхуков.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationWebhooks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationWebhooksDlq
     *
     * Получить сообщения DLQ вебхуков.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationWebhooksDlq()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationWebhooksEvents
     *
     * Получить каталог событий вебхуков.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationWebhooksEvents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfilesProfileIdIntegrationsIntegrationWebhooksId
     *
     * Получить вебхук.
     *
     */
    public function testGetProfilesProfileIdIntegrationsIntegrationWebhooksId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProfilesProfileIdIntegrationsIntegrationWebhooksId
     *
     * Обновить вебхук.
     *
     */
    public function testPatchProfilesProfileIdIntegrationsIntegrationWebhooksId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationWebhookSubscribe
     *
     * Подписать входящий webhook интеграции.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationWebhookSubscribe()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationWebhookUnsubscribe
     *
     * Отключить входящий webhook интеграции.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationWebhookUnsubscribe()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationWebhooks
     *
     * Создать вебхук.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationWebhooks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationWebhooksCheck
     *
     * Проверить адрес вебхука.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationWebhooksCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationWebhooksDlqRedrive
     *
     * Повторно отправить сообщения из DLQ.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationWebhooksDlqRedrive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProfilesProfileIdIntegrationsIntegrationWebhooksIdTest
     *
     * Отправить тестовый вебхук.
     *
     */
    public function testPostProfilesProfileIdIntegrationsIntegrationWebhooksIdTest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
